# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
  displayName: 'Restore and save artifact based on: **/package-lock.json, !**/node_modules/**/package-lock.json'
  inputs:
    keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json'
    targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
    vstsFeed: '0657ed4c-f114-42ec-96c7-f2bb62b84e13'
    platformIndependent: true

- bash: yarn install
  displayName: Install Dependencies

- bash: yarn run build
  displayName: Build application

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'