# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  displayName: Cache
  inputs:
    key: './yarn.lock'
    path: './node_modules'
    cacheHitVar: CacheRestored

- bash: yarn install
  displayName: Install Dependencies

- bash: yarn run build
  displayName: Build application

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'